### ISSUE TITLE
Is there a way to make this script start automatically when starting any video?

### ISSUE THREAD

**Issue by neko47834** [mhtvsSFrpHdE/AnimeAnyK-mpv#13]
First of all thank you very much for this script I use Anime4k in a standard way so it works great for me to load the necessary scripts depending on the resolution of the video, only that I would like this script to always start in each video since I have to copy the file "Anime4K_jbgyampcwu" each anime folder or type the command to activate since I watch a lot of anime broadcast with Streamlink. thank you

**Comment by mhtvsSFrpHdE** [comment]
The script is designed to "Non-invasive" at the beginning (only work when user request), so it does can be annoying for people who indeed have vast amount of anime.

You can use text editor supports "UTF-8 no BOM" format to open `AnimeAnyK.lua`,  
for example, `notepad.exe` after Windows 10 22H2, almost any Linux text editor, notepad++, Visual Studio Code.

In text editor, search `function Core_jbgyampcwu.GetIndicatorFileStatus()`,  
between `local indicatorFileFullPath...` and `-- Try indicator file exist`,  
insert a new line `return true, indicatorFileFullPath`,
delete all line until keyword `end`

It will look like this:

```
... (other code)

function Core_jbgyampcwu.GetIndicatorFileStatus()
    ... (other code)
    -- Fill parent folder
    local indicatorFileFullPath = mpUtils.join_path(fileParentFolder, indicatorFileName)
    return true, indicatorFileFullPath
end

...(other code)
```

Then the script should enable on any video you've opened.  
When you press script bind key, you can clear your GLSL, but not able to use it to enable again.  
In this case, close video player and open again to get GLSL enabled.

**Comment by neko47834** [comment]
thank you very much, it works quite well :)

**Comment by mhtvsSFrpHdE** [comment]
Hi, 1.2 was released, so you don't need to hack the script anymore.

[Download directly](https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/raw/main/AnimeAnyK.lua) from master branch or look at [Release](https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/releases/tag/1.2) page.

Go to line 25, change from `AlwaysOn = false,` to `AlwaysOn = true,`.
