### ISSUE TITLE
Getting Cannot open file after pressing keybind

### ISSUE THREAD

**Issue by RaulRohjans** [mhtvsSFrpHdE/AnimeAnyK-mpv#2]
Hello, I have setup the script like shown in the tutorial and when I press the key-bind I get a cannot open file error for the shaders. Im running Manjaro Linux.

Error:
![Screenshot from 2021-12-31 22-28-31](https://user-images.githubusercontent.com/77687494/147840296-e042c86c-09fa-4d69-a527-5a5f8b73ba14.png)

shaders folder:
![Screenshot from 2021-12-31 22-29-12](https://user-images.githubusercontent.com/77687494/147840299-6dd5a770-640f-43c4-8333-8fcd415de256.png)

The paths seem to be correct but for some reason it still can't open them.

**Comment by mhtvsSFrpHdE** [comment]
My command were copied from official example "Optimized shaders for lower-end GPU:" at here

https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md

The script should send the exact same command to mpv,  
but in your setup there are files not found error.  
Can you use these official command to enable Anime4K?  
In my opinion, your log are very different, compare to   
official command at `/home/raul/.config/mpv/shaders`.  
The official command use relative path. I don't know why yours is full path.

If you can use official command, then this is my script problem.  
If official command can't even work,  
I think there is an installation or configuration issue need to be resolved by yourself first.

I suggest first check why mpv try to access `/home/raul/.config/mpv/shaders`.  
Do you have read permissions? For example,  
unpack zip file via `sudo` prefix can cause only root have read permissions.  
Or you are using custom script command feature but provided wrong command?  
The script will send the user command as is without any syntax checking.

**Comment by RaulRohjans** [comment]
Sorry for the time I took to answer, looks like it was something super simple.
In the config file where the keybind to activate the shaders is, the paths are separated by ';' but this only works for Windows. In order to make this work on Linux you have to use ':' instead.

**Comment by mhtvsSFrpHdE** [comment]
@RaulRohjans I created a patch to support Linux/Unix OS,  
but I don't have a Linux PC with graphics card installed.

You can help test it and report if anything goes wrong.  
This will also benefit to other Linux users.

Download new `.lua` file from this branch:
https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/tree/linux-support

Or download full zip:
https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/archive/refs/heads/linux-support.zip

**Comment by mhtvsSFrpHdE** [comment]
@RaulRohjans If you can enable shader in `1.1.3` without path problems, please update to version `1.1.4`.  
Any past version now is deprecated because of undefined behavior.  
See release page for more information.
