### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/AnimeAnyK-mpv#3]
https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/issues/2

Path separator need to redesign.

**Comment by mhtvsSFrpHdE** [comment]
What about
```
if linux
    replace every ";" with ":"
```

Your code is cursed.

**Comment by vsedov** [comment]
yes and on : Line 297 , 

```lua
mp.command('no-osd change-list glsl-shaders clr "" ; show-text "GLSL shaders cleared"')
```
and  line 107 

``` lua
 local commandShowTextConst = "; show-text "
```

this should work for both windows and linux

**Comment by mhtvsSFrpHdE** [comment]
@vsedov on Windows, `; show-text` is fine.

So this seems I only need to replace path list separator from `;` to `:` on Linux/Unix,  
but don't need to replace command separator from `;` to `:`.

**Comment by mhtvsSFrpHdE** [comment]
Patch submitted to main branch https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv/commit/dbd62f66eb7a2cc45604d0708f009ae2d3c134c9
